### ISSUE TITLE
Create sign in api

### ISSUE THREAD

**Issue by erivansousa** [erivansousa/egtmanager_service#7]
This api should receive a pair of email and password and should return a pair of JWT authentication token and a refresh token, they should be saved on the user database registry

API: `/account/signin`
body:

``
{
	"email": "nebwemail@egtm.com",
	"password": "blablabla"
}
``

return:

``
{
	"token": "xxxxxxxxxxxxxxxxxxx",
	"refresh_token": "xxxxxxxxxxxxxx"
}
``

**Comment by 0IHI0** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
